### ISSUE TITLE
Bug when you change default schema with PostgreSQL

### ISSUE THREAD

**Issue by mlecoeuvre** [irstv/orbisgis#673]
By default when you connect with OrbisGIS to the PostgreSQL/ PostGIS database the schema used is public.
You can change the default schema by an other schema (`SET search_path TO schema`) but you have several problems.

#### « geometry_columns » doesn't exist
When you execute this request you have a warn message:
```java
WARN [SwingWorker-pool-1-thread-1] (SourceListModel.java:271) - Geometry columns information of tables are not available
org.postgresql.util.PSQLException: ERREUR: la relation « geometry_columns » n'existe pas
  Position : 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:560)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
	at com.sun.proxy.$Proxy43.executeQuery(Unknown Source)
	at org.orbisgis.postgis_jts_osgi.StatementWrapper.executeQuery(StatementWrapper.java:51)
	at org.h2gis.utilities.wrapper.StatementWrapper.executeQuery(StatementWrapper.java:23)
	at org.orbisgis.view.geocatalog.SourceListModel.readDatabase(SourceListModel.java:265)
	at org.orbisgis.view.geocatalog.SourceListModel$ReadDataManagerOnSwingThread.doInBackground(SourceListModel.java:164)
	at org.orbisgis.view.geocatalog.SourceListModel$ReadDataManagerOnSwingThread.doInBackground(SourceListModel.java:155)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
This warn is logical because  the system table `geometry_columns` exists only in schema "public" but it's used by all schema.

#### Lost type of table
All tables have lost the information on their type (geometric or alphanumeric). It's logical because the relation with `geometry_columns` have lost.

Maybe the solution is to refer always at `public.geometry_columns` for table system.

**Comment by ebocher** [comment]
@gpetit ?

**Comment by nicolas-f** [comment]
Now this issue have to be moved to H2GIS for SpatialUtilities.getTableGeometry
