### ISSUE TITLE
Error when drawing a linked shape files

### ISSUE THREAD

**Issue by gpetit** [irstv/orbisgis#749]
In a brand new workspace I linked some shape files.
Then I drag & drop two layers in the TOC.
When OG is drawing, I obtained this error message : 

```
ERROR [Thread-142] (RunnableBackgroundJob.java:73) - Erreur fatale lors du processus Drawing
java.lang.IllegalArgumentException: org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT PK FROM "BATI_INDIFFERENCIE"  [57014-182]
	at org.orbisgis.corejdbc.internal.ReadRowSetImpl.cachePrimaryKey(ReadRowSetImpl.java:172)
	at org.orbisgis.corejdbc.internal.ReadRowSetImpl.execute(ReadRowSetImpl.java:431)
	at org.orbisgis.corejdbc.internal.ReadRowSetImpl.initialize(ReadRowSetImpl.java:422)
	at org.orbisgis.corejdbc.internal.ReadRowSetImpl.initialize(ReadRowSetImpl.java:410)
	at org.orbisgis.mapeditor.map.CachedResultSetContainer.getResultSetProvider(CachedResultSetContainer.java:104)
	at org.orbisgis.coremap.renderer.Renderer.drawStyle(Renderer.java:184)
	at org.orbisgis.coremap.renderer.Renderer.drawVector(Renderer.java:151)
	at org.orbisgis.coremap.renderer.Renderer.draw(Renderer.java:353)
	at org.orbisgis.coremap.renderer.Renderer.draw(Renderer.java:300)
	at org.orbisgis.mapeditor.map.MapControl$Drawer.run(MapControl.java:363)
	at org.orbisgis.view.background.Job.run(Job.java:87)
	at org.orbisgis.view.background.RunnableBackgroundJob.run(RunnableBackgroundJob.java:71)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Statement was canceled or the session timed out; SQL statement:
SELECT PK FROM "BATI_INDIFFERENCIE"  [57014-182]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.Command.checkCanceled(Command.java:142)
	at org.h2.command.Prepared.checkCanceled(Prepared.java:278)
	at org.h2.command.Prepared.setCurrentRowNumber(Prepared.java:338)
	at org.h2.command.dml.Select.queryFlat(Select.java:533)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:644)
	at org.h2.command.dml.Query.query(Query.java:322)
	at org.h2.command.dml.Query.query(Query.java:290)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:90)
	at org.h2.command.Command.executeQuery(Command.java:197)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:79)
	at org.h2gis.utilities.wrapper.StatementWrapper.executeQuery(StatementWrapper.java:23)
	at org.orbisgis.corejdbc.internal.ReadRowSetImpl.cachePrimaryKey(ReadRowSetImpl.java:160)
	... 12 more
```

**Comment by ebocher** [comment]
@gpetit ?

**Comment by gpetit** [comment]
Seems good
